[package]
name = "shouxtech/soma"
description = ""
version = "1.0.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["src", "src/**", "default.project.json", "wally.toml", "wally.lock"]
exclude = ["**"]

[dependencies]